# This file was adapted from work by Keith James (keithj). The original source
# can be found as part of the wtsi-npg/data_handling project here:
#
#   https://github.com/wtsi-npg/data_handling
#
# iRODS setup added by Iain Bancarz (ib5), adapted from baton:
#   https://github.com/wtsi-npg/baton

sudo: required

language: perl

perl:
  - "5.16"

addons:
  postgresql: "9.3"

env:
  global:
    - DNAP_UTILITIES_VERSION="0.5.2"
    - secure: cDfB188ECmloGfScZQezqwiFef7l+gXgn2RiTOxINriy9wYS6RmZxuZBHGuR36u7QV3QEJtMdihyQ+XBN2eQPf5jULQXV15t7gArXEVPzzF8i+f8MTgVHugU3TqmPLQkY94wBBbpzvRD9xCAC/uNiQcLLwuD2SjPfTXkqgqqtd0=
    - PGVERSION="9.3"
    - JANSSON_VERSION="2.7"
    - CK_DEFAULT_TIMEOUT=20
    - PLATFORM=ubuntu12
    - ARCH=x86_64
    - RENCI_URL=ftp://ftp.renci.org
    - WTSI_NPG_URL=https://github.com/wtsi-npg/irods
    - PG_PLUGIN_VERSION=1.9
    - BATON_VERSION="0.16.4"
  matrix:
    - TRAVIS_NODE_VERSION="0.12.9"
    - TRAVIS_NODE_VERSION="4.4.2"

before_install:
  - ./.travis/before_install.sh

install:
  - ./.travis/install.sh

before_script:
  - source ./.travis/before_script.sh
  - ienv
  - ilsresc -l
  - ils

script:
  - ./.travis/script.sh

