language: node_js
node_js :
 - "0.12"
before_install:
 - cd npg_qc_viewer/root/static
before_script:
 - npm install -g bower
 - bower install
 - npm install -g qunit-phantomjs-runner@2.1.0
script: phantomjs /home/travis/.nvm/versions/node/v0.12.2/lib/node_modules/qunit-phantomjs-runner/runner.js test/test.html

