sudo: required

language: perl

perl:
  - "5.26-shrplib"

dist:
  - bionic

addons:
  apt:
    packages:
      - libgd2-xpm-dev 

env:
  global:
    - TRAVIS_NODE_VERSION="6.12.2"
    - TRAVIS_NPM_VERSION="4.5.0"
    - TRAVIS_YARN_VERSION="1.3.2"
    - TRAVIS_PYTHON_VERSION="2.7"
    - WTSI_NPG_GITHUB_URL=https://github.com/wtsi-npg
    - CONDA_CHANNEL=https://dnap.cog.sanger.ac.uk/npg/conda/prod/generic
    - CONDA_TEST_ENV=test-environment

before_install:
  - ./.travis/before_install_conda.sh
  - ./.travis/before_install.sh

install:
  - ./.travis/install.sh

script:
  - export PATH="$HOME/miniconda/bin:$PATH"
  - source activate "$CONDA_TEST_ENV"
  - ./.travis/script.sh
