# This file was adapted from work by Keith James (keithj). The original source
# can be found as part of the wtsi-npg/data_handling project here:
#
#   https://github.com/wtsi-npg/data_handling
#
# iRODS setup added by Iain Bancarz (ib5), adapted from baton:
#   https://github.com/wtsi-npg/baton

sudo: required

language: perl

perl:
  - "5.16"
  - "5.22-shrplib"

addons:
  postgresql: "9.3"

env:
  global:
    - secure: cDfB188ECmloGfScZQezqwiFef7l+gXgn2RiTOxINriy9wYS6RmZxuZBHGuR36u7QV3QEJtMdihyQ+XBN2eQPf5jULQXV15t7gArXEVPzzF8i+f8MTgVHugU3TqmPLQkY94wBBbpzvRD9xCAC/uNiQcLLwuD2SjPfTXkqgqqtd0=
    - PGVERSION="9.3"
    - JANSSON_VERSION="2.7"
    - DISPOSABLE_IRODS_VERSION="1.1"
    - RENCI_FTP_URL=ftp://ftp.renci.org
    - WTSI_NPG_GITHUB_URL=https://github.com/wtsi-npg
    - BATON_VERSION="0.16.4"
    - DNAP_UTILITIES_VERSION="0.5.3"
  matrix:
    - TRAVIS_NODE_VERSION="4.5.0"
    - IRODS_VERSION=3.3.1 IRODS_RIP_DIR=/usr/local/irods
    - IRODS_VERSION=4.1.9 PG_PLUGIN_VERSION=1.9 PLATFORM=ubuntu12

before_install:
  - ./.travis/before_install.sh

install:
  - ./.travis/install.sh

script:
  - ienv
  - ils
  - ilsresc -l
  - ./.travis/script.sh

